exclude_patterns:
- "docs/"
<<<<<<< HEAD
- "**/views/"
- "**/*.blade.php"
- "**/FontAwesome.php"
- "src/assets/"
- "src/configs/"
- "src/database/"
- "**/localization/"
- "**/Seeder.php"
- "**/*_routes.php"
- "**/*Form.php"
=======
- "src/views/"
- "src/assets/"
- "src/configs/"
- "src/database/"
- "src/localization/"
>>>>>>> 5.4.0
- "src/laravel-filemanager/"
- "**/*.js"
- "**/*.MD"